apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: flask
  source:
    repoURL: https://github.com/wwdreda/vault-gitops-lab.git
    targetRevision: HEAD
    path: vault-lab/charts/flask-app
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
