apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/wwdreda/vault-gitops-lab.git
    targetRevision: HEAD
    path: demo-app
    plugin:
      name: avp
  project: default
  syncPolicy:
    automated: {}
